[package]
name = "libpoke"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
lockchain-core = "0.2.1"
serde_derive = "1.0"
serde = "1.0"

yubico = "0.4"
toml = "0.4"
rand = "0.5"
hex = "0.3"